# Introduction

You'll learn all about **[pandas](https://pandas.pydata.org)**, the most popular Python library for data analysis.

Along the way, you'll complete several hands-on exercises with real-world data.

In this tutorial, you will learn how to create your own data, along with how to work with data that already exists.  

# Getting started

To use pandas, you'll typically start with the following line of code.

In [5]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (1.4.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\navde\appdata\roaming\python\python39\site-packages (from pandas) (2022.7.1)
Requirement already satisfied: numpy>=1.18.5 in c:\programdata\anaconda3\lib\site-packages (from pandas) (1.21.5)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [2]:
import pandas as pd

# Creating data

There are two core objects in pandas: the **DataFrame** and the **Series**.

### DataFrame

A DataFrame is a table. It contains an array of individual *entries*, each of which has a certain *value*. Each entry corresponds to a row (or *record*) and a *column*.

For example, consider the following simple DataFrame:

In [ ]:
pd.DataFrame()

In [14]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

   Yes   No
0   50  131
1   21    2

In this example, the "0, No" entry has the value of 131. The "0, Yes" entry has a value of 50, and so on.

DataFrame entries are not limited to integers. For instance, here's a DataFrame whose values are strings:

In [15]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})

             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

In [10]:
pd.DataFrame({'Name':['ABC','DEF'],'Department':['Dep1','Dep2']})

  Name Department
0  ABC       Dep1
1  DEF       Dep2

We are using the `pd.DataFrame()` constructor to generate these DataFrame objects. The syntax for declaring a new one is a dictionary whose keys are the column names (`Bob` and `Sue` in this example), and whose values are a list of entries. This is the standard way of constructing a new DataFrame, and the one you are most likely to encounter.

The dictionary-list constructor assigns values to the *column labels*, but just uses an ascending count from 0 (0, 1, 2, 3, ...) for the *row labels*. Sometimes this is OK, but oftentimes we will want to assign these labels ourselves.

The list of row labels used in a DataFrame is known as an **Index**. We can assign values to it by using an `index` parameter in our constructor:

In [16]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

In [ ]:
# pd.DataFrame()

### Series

A Series, by contrast, is a sequence of data values. If a DataFrame is a table, a Series is a list. And in fact you can create one with nothing more than a list:

In [6]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

A Series is, in essence, a single column of a DataFrame. So you can assign row labels to the Series the same way as before, using an `index` parameter. However, a Series does not have a column name, it only has one overall `name`:

In [7]:
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

The Series and the DataFrame are intimately related. It's helpful to think of a DataFrame as actually being just a bunch of Series "glued together". We'll see more of this in the next section of this tutorial.

# Reading data files

Being able to create a DataFrame or Series by hand is handy. But, most of the time, we won't actually be creating our own data by hand. Instead, we'll be working with data that already exists.

Data can be stored in any of a number of different forms and formats. By far the most basic of these is the humble CSV file. When you open a CSV file you get something that looks like this:

```
Product A,Product B,Product C,
30,21,9,
35,34,1,
41,11,11
```

So a CSV file is a table of values separated by commas. Hence the name: "Comma-Separated Values", or CSV.

Let's now set aside our toy datasets and see what a real dataset looks like when we read it into a DataFrame. We'll use the `pd.read_csv()` function to read the data into a DataFrame. This goes thusly:

In [12]:
cd()

[WinError 2] The system cannot find the file specified: '()'
C:\Personal\Navdeep\Training\BA\5 - BT AI\Python\6. Pandas\Kaggle

In [13]:
# pd.

In [3]:
df=pd.read_csv('C:\\Personal\\Navdeep\\Training\\BA\\5 - BT AI\\Python\\6. Pandas\\data\\winemag-data-130k-v2_filtered.csv')

In [5]:
df.head(2)

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos

In [6]:
df.shape

(9998, 14)

In [7]:
df.tail(2)

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
9996,9996,US,"Smoky and savory, with sharp acidity under bla...",NaN,89,22.0,Washington,Columbia Valley (WA),Columbia Valley,Paul Gregutt,@paulgwine,Seven Hills 2007 Tempranillo (Columbia Valley ...,Tempranillo,Seven Hills
9997,9997,France,The style at Domaines Ott has changed to becom...,Château de Selle,89,43.0,Provence,Côtes de Provence,NaN,Roger Voss,@vossroger,Domaines Ott 2009 Château de Selle Rosé (Côtes...,Rosé,Domaines Ott

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9998 entries, 0 to 9997
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             9998 non-null   int64
 1   country                9993 non-null   object
 2   description            9998 non-null   object
 3   designation            7090 non-null   object
 4   points                 9998 non-null   int64
 5   price                  9313 non-null   float64
 6   province               9993 non-null   object
 7   region_1               8305 non-null   object
 8   region_2               3898 non-null   object
 9   taster_name            8017 non-null   object
 10  taster_twitter_handle  7662 non-null   object
 11  title                  9998 non-null   object
 12  variety                9998 non-null   object
 13  winery                 9998 non-null   object
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB

In [9]:
df.describe()

       Unnamed: 0       points        price
count  9998.00000  9998.000000  9313.000000
mean   4998.50000    88.395179    35.505315
std    2886.31833     3.010828    44.300746
min       0.00000    80.000000     4.000000
25%    2499.25000    86.000000    17.000000
50%    4998.50000    88.000000    25.000000
75%    7497.75000    90.000000    42.000000
max    9997.00000   100.000000  1900.000000

In [10]:
df.columns

Index(['Unnamed: 0', 'country', 'description', 'designation', 'points',
       'price', 'province', 'region_1', 'region_2', 'taster_name',
       'taster_twitter_handle', 'title', 'variety', 'winery'],
      dtype='object')

In [15]:
# df['country']
# df.country

# ls=['country', 'description', 'designation', 'points',
#        'price', 'province']

df_subset=df[['country', 'description', 'designation', 'points','price', 'province']]

In [16]:
df_subset.head(2)

,country,description,designation,points,price,province
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro

In [18]:
df_subset.country.unique()

array(['Italy', 'Portugal', 'US', 'Spain', 'France', 'Germany',
       'Argentina', 'Chile', 'Australia', 'Austria', 'South Africa',
       'New Zealand', 'Israel', 'Hungary', 'Greece', 'Romania', 'Mexico',
       'Canada', nan, 'Turkey', 'Czech Republic', 'Slovenia',
       'Luxembourg', 'Croatia', 'Georgia', 'Uruguay', 'England',
       'Lebanon', 'Serbia', 'Brazil', 'Moldova', 'Morocco', 'Peru',
       'India', 'Bulgaria', 'Cyprus', 'Armenia'], dtype=object)

In [23]:
df_us_price_filtered=df_subset[(df_subset['country']=='US') & (df_subset['price']>100)]

In [24]:
df_us_price_filtered['price'].describe()

count     84.000000
mean     143.583333
std       35.812836
min      105.000000
25%      120.000000
50%      132.500000
75%      150.000000
max      300.000000
Name: price, dtype: float64

In [27]:
df_us_price_filtered['country'].unique()

array(['US'], dtype=object)

In [28]:
df_us_price_filtered.to_csv('C:\\Personal\\Navdeep\\Training\\BA\\5 - BT AI\\Python\\6. Pandas\\df_us_price_filtered.csv')

In [17]:
df.head(2)

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos

In [31]:
ls=['country','description','region_1']
df_filtered=df[ls]

In [44]:
df.designation.value_counts()


# Country = US
# Designation = Reserve

Reserve                              149
Estate                               115
Reserva                               77
Riserva                               52
Estate Grown                          49
                                    ...
Meandro do Vale Meão                   1
The Wah                                1
Evidência                              1
Vineyard Series Clifton Vineyards      1
Château de Selle                       1
Name: designation, Length: 5341, dtype: int64

In [38]:
# df[]
df_country=df[df['country']=='Italy']

In [41]:
df[(df['region_1']=='Etna') & (df['designation']=='Rosso')]

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
13,13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
861,861,Italy,"Pressed wild flower, hay, fennel and ripe berr...",Rosso,90,30.0,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Graci 2015 Rosso (Etna),Nerello Mascalese,Graci
9959,9959,Italy,"Aromas of toasted oak, mint, vanilla and dried...",Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2011 Rosso (Etna),Red Blend,Nicosia

In [39]:
df_country.head(2)

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo

In [30]:
# df[ls]

In [27]:
df_filtered.shape

(9998, 3)

In [28]:
df.shape

(9998, 14)

In [8]:
wine_reviews = pd.read_csv("winemag-data-130k-v2.csv")

We can use the `shape` attribute to check how large the resulting DataFrame is:

In [9]:
wine_reviews.shape

(129971, 14)

So our new DataFrame has 130,000 records split across 14 different columns. That's almost 2 million entries!

We can examine the contents of the resultant DataFrame using the `head()` command, which grabs the first five rows:

In [29]:
wine_reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

The `pd.read_csv()` function is well-endowed, with over 30 optional parameters you can specify. For example, you can see in this dataset that the CSV file has a built-in index, which pandas did not pick up on automatically. To make pandas use that column for the index (instead of creating a new one from scratch), we can specify an `index_col`.

In [27]:
wine_reviews = pd.read_csv("winemag-data-130k-v2.csv", index_col=0)
wine_reviews.head(2)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos

In [26]:
wine_reviews = pd.read_csv("winemag-data-130k-v2.csv", index_col=1)
wine_reviews.head(2)

,Unnamed: 0,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
country,,,,,,,,,,,,,
Italy,0,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
Portugal,1,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos

In [30]:
wine_reviews.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 129971 entries, 0 to 129970
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   country                129908 non-null  object
 1   description            129971 non-null  object
 2   designation            92506 non-null   object
 3   points                 129971 non-null  int64
 4   price                  120975 non-null  float64
 5   province               129908 non-null  object
 6   region_1               108724 non-null  object
 7   region_2               50511 non-null   object
 8   taster_name            103727 non-null  object
 9   taster_twitter_handle  98758 non-null   object
 10  title                  129971 non-null  object
 11  variety                129970 non-null  object
 12  winery                 129971 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 13.9+ MB

In [31]:
wine_reviews.describe()

              points          price
count  129971.000000  120975.000000
mean       88.447138      35.363389
std         3.039730      41.022218
min        80.000000       4.000000
25%        86.000000      17.000000
50%        88.000000      25.000000
75%        91.000000      42.000000
max       100.000000    3300.000000

In [24]:
# wine_reviews.loc['US']

In [23]:
#Filter data only for CA

cfdf=wine_reviews[wine_reviews['province']=='California']

In [34]:
df_us=df[(df['country']=='US') | (df['designation']=='Reserve')]

In [32]:
df_us['country'].nunique()

1

In [33]:
df['country'].value_counts()

US                4180
France            1587
Italy             1546
Spain              493
Portugal           468
Chile              399
Argentina          316
Austria            243
Australia          192
Germany            157
South Africa       132
New Zealand        111
Greece              32
Israel              29
Canada              20
Romania             17
Hungary             12
Bulgaria             8
Turkey               7
Uruguay              5
Mexico               5
Czech Republic       4
Croatia              4
Lebanon              4
Slovenia             4
Moldova              4
England              3
Georgia              2
Brazil               2
India                1
Cyprus               1
Serbia               1
Peru                 1
Morocco              1
Luxembourg           1
Armenia              1
Name: country, dtype: int64

In [49]:
df_us.to_csv('wine_data_us.csv')

In [50]:
cd()

[WinError 2] The system cannot find the file specified: '()'
C:\Personal\Navdeep\Training\BA\5 - BT AI\Python\6. Pandas\Kaggle

In [22]:
#Write data from pandas to csv

cfdf.to_csv('california_wine.csv')